version: '3.8'

services:
  bot:
    build: .
    env_file: .env
    depends_on:
      - db
    command: >
      sh -c "
        until alembic stamp head && alembic revision --autogenerate && 
              alembic upgrade head; do
          echo 'Waiting for database...';
          sleep 2;
        done &&
        pybabel compile -d locale -D lang &&
        python app.py"
    restart: always

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
