name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USER }}/telegram-bot:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH Agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to DigitalOcean
      run: |
        # Ensure the network exists
        docker network inspect telegram_network >/dev/null 2>&1 || docker network create telegram_network
  
        # Pull the latest image
        docker pull ${{ secrets.DOCKER_USERNAME }}/telegram-bot:latest
  
        # Stop and remove old container if exists
        docker ps -q --filter "name=telegram_bot" | grep -q . && docker stop telegram_bot && docker rm telegram_bot
  
        # Run the new container
        docker run -d --name telegram_bot \
          --env-file /root/n50_bellissimo/.env \
          --network=telegram_network \
          --restart=always \
          ${{ secrets.DOCKER_USERNAME }}/telegram-bot:latest \
          sh -c "alembic upgrade head && pybabel compile -d locale -D lang && python app.py"
  
        # Optional: Display logs for debugging
        sleep 5
        docker logs telegram_bot

